---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${hostname}
  name: mvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvn
  template:
    metadata:
      labels:
        app: mvn
    spec:
      volumes:
        - {name: data-volume, hostPath: {path: /root/lib/0.mvn, type: Directory}}
      containers:
        - name: mvn
          image: container.${domain}/org.apache.archiva:${tag}
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 8080}
          volumeMounts:
            - {name: data-volume, subPath: data,         mountPath: /org.apache.archiva/data}
            - {name: data-volume, subPath: repositories, mountPath: /org.apache.archiva/repositories}

---
apiVersion: v1
kind: Service
metadata:
  namespace: ${hostname}
  name: mvn
spec:
  type: LoadBalancer
  selector:
    app: mvn
  ports:
    - {protocol: TCP, port: 8080}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${hostname}
  name: mvn
spec:
  rules:
    - host: mvn.${domain}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mvn
                port:
                  number: 8080
