#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

base_path='/var/git'

git daemon \
  --export-all \
  --base-path="${base_path}" \
  "${base_path}" &

lighttpd -f /etc/lighttpd/lighttpd.conf

tail -f /dev/null
