#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

(

  hook_name="${0##*/}"

  stdin=($(cat /dev/stdin))

  function _debug() {
    printf "\e[2m"
    echo '---'
    echo "${0}:"
    echo '  env:'
    export | sed 's/declare -x /    - /g'
    echo '  args:'
    for item in "${@}"; do
      echo "    - ${item}"
    done
    echo '  stdin:'
    for item in "${stdin[@]}"; do
      echo "    - ${item}"
    done
    printf "\e[0m"
  }

  function _validate() {
    (

      grep_opts=()
      grep_opts+=('-n')
      grep_opts+=('-E')
      grep_opts+=('-e' "${USER}")
      grep_opts+=('-e' "${HOME}")

      {
#       git diff          --name-only
        git diff --cached --name-only
      } | sort --unique | while read file; do
        ! git show ":${file}" | grep "${grep_opts[@]}" | awk -v f="${file}" '{print f " #" $0}'
      done

    )
  }

  #----------------------------------------------------------------
  # client hook

  if [[ 'pre-commit' == "${hook_name}" ]]; then
    _debug
    _validate

  elif [[ 'post-commit' == "${hook_name}" ]]; then
    _debug

  elif [[ 'pre-push' == "${hook_name}" ]]; then
    _debug

  #----------------------------------------------------------------
  # remote hook

  elif [[ 'pre-receive' == "${hook_name}" ]]; then
    _debug
#   _validate

  elif [[ 'post-receive' == "${hook_name}" ]]; then
    _debug
  fi

)
