#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# TODO: 引数ではなく標準入力からパラメータが渡ってくる
stdin=($(cat /dev/stdin))

# debug
if true; then
  printf "\e[2m"
  echo   '---'
  echo   'exec:'
  echo   "  pwd: ${PWD}"
  echo   "  cmd: ${BASH_SOURCE:-0}"
  echo   '  stdin:'
  for item in "${stdin[@]}"; do
    echo "    - ${item}"
  done
  # TODO: indent
  echo   '  export:'
  export
  printf "\e[0m"
fi

exit 0
