#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

stdin=($(cat /dev/stdin))

printf "\e[2m"

  echo '---'
  echo "${0}:"
  echo '  env:'
  export | grep '^declare -x GIT_' | sed 's/declare -x /    - /g'
  echo '  args:'
  for item in "${@}"; do
    echo "    - ${item}"
  done
  echo '  stdin:'
  for item in "${stdin[@]}"; do
    echo "    - ${item}"
  done

printf "\e[0m"

exit 0
