#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

printf "\e[2m"

  echo   '---'
  echo   'env:'
  export | sed 's/declare -x /  - /g'

  echo   "${0}:"
  echo   "  pwd: ${PWD}"
  echo   "  cmd: ${BASH_SOURCE:-0}"
  echo   '  args:'
  for item in "${@}"; do
    echo "    - ${item}"
  done

printf "\e[0m"

fpr ci || true
