keyid-format      long
with-fingerprint
with-fingerprint
with-keygrip
#with-colons

cert-digest-algo  sha512
cipher-algo       aes256
compress-algo     zlib

list-options      show-uid-validity 
verify-options    show-uid-validity

use-agent

# /etc/profile.d/0.shで定義
#default-key       =0
#default-recipient =0
