#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

(
  pushd "${HOME}" &> /dev/null

    is_venv

    mkdir -p './blob'

    source '/etc/os-release'

    arch="$(dpkg --print-architecture)"
    machine_id="$(machine_id)"
    boot_id="$(boot_id)"
    openpgp4fpr="$(openpgp4fpr)"

    entrypoint_yml="$(cat './entrypoint.yml' | varsubst)"
    compose_yml="$(   cat './compose.yml'    | varsubst)"

    # mnt
#   mnt
    echo "${entrypoint_yml}" | yq -rc '.entrypoint.mnt[]?' | while read item; do

      key="$(echo "${item}" | yq -rc .key)"
      dir="$(echo "${item}" | yq -rc .dir)"

      mnt "${key}" "${dir}"

    done

    # machine_id
    if [[ ! -f "./blob/${machine_id}" ]]; then

      sudo -v -n

      # apt repo
      echo "${entrypoint_yml}" | yq -rc '.entrypoint.apt.repo[]?' | while read item; do

        name="$(  echo "${item}" | yq -rc .name)"
        pub="$(   echo "${item}" | yq -rc .pub)"
        source="$(echo "${item}" | yq -rc .source)"

        pub_file="/etc/apt/keyrings/${name}.gpg"
        src_file="/etc/apt/sources.list.d/${name}.list"

        curl -fsSL "${pub}"                          | sudo tee "${pub_file}" > /dev/null
        echo "deb [signed-by=${pub_file}] ${source}" | sudo tee "${src_file}" > /dev/null

      done

      # apt
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y $(echo "${entrypoint_yml}" | yq -rc '.entrypoint.apt.pkg[]?')

      # pip
      {
        echo "${entrypoint_yml}" | yq -rc '.entrypoint.pip.pkg[]?'
        cat './.venv/requirements.txt'
      } | sort --unique | pip install --upgrade --requirement '/dev/stdin'

      # src
      echo "${entrypoint_yml}" | yq -rc '.entrypoint.src[]?' | while read item; do
        wpull "${item}"
      done

      # lib
      echo "${entrypoint_yml}" | yq -rc '.entrypoint.lib[]?' | while read item; do
        wpull "${item}"
      done

      # opt
#     echo "${entrypoint_yml}" | yq -rc '.entrypoint.opt[]?' | while read item; do
#       wpull "${item}"
#     done

      build

      touch "./blob/${machine_id}"

    fi

    # boot_id
    if [[ ! -f "./blob/${boot_id}" ]]; then

      sudo -v -n

      sudo nvidia-ctk cdi generate --output='/etc/cdi/nvidia.yaml'

      touch "./blob/${boot_id}"

    fi

    # tmux
    if type tmux &> /dev/null && [[ ! -v TMUX ]]; then

      if ! tmux list-sessions &> /dev/null; then
        tmux new-session -d
#       tmux split-window -h watch -bctd htop
        tmux select-pane -t 0
        tmux send-keys './entrypoint' C-m
      fi

      tmux attach-session

    fi

    if ! type tmux &> /dev/null || [[ -v TMUX && '0.0.0' == "$(tmux display-message -p '#S.#I.#P')" ]]; then

      # fpr
#     gpg --with-colons --list-secret-keys | grep -A 1 ^sec: | grep ^fpr: | cut -d ':' -f 10 | while read fpr; do
      gpg --with-colons --list-keys        | grep -A 1 ^pub: | grep ^fpr: | cut -d ':' -f 10 | while read fpr; do

        mkdir -p "./blob/${fpr}"

#       gpg --batch --yes --export-secret-keys --armor --output "./blob/${fpr}/key" "0x${fpr}" 2> /dev/null || true
        gpg --batch --yes --export             --armor --output "./blob/${fpr}/pub" "0x${fpr}"

      done

      # git
#     git config --global user.name       "$(gpg --with-colons --list-keys        "0x${openpgp4fpr}" |                 grep ^uid: | cut -d : -f 10 | sed -r 's/.../\1/g')"
#     git config --global user.email      "$(gpg --with-colons --list-keys        "0x${openpgp4fpr}" |                 grep ^uid: | cut -d : -f 10 | sed -r 's/.../\2/g')"
      git config --global user.signingkey "$(gpg --with-colons --list-secret-keys "0x${openpgp4fpr}" | grep -A 1 :s: | grep ^fpr: | cut -d : -f 10)"

      # venv
      pip freeze | sed 's/=.*//g' > './.venv/requirements.txt'

      sudo -v -n

      # compose down
      echo "${compose_yml}" | podman-compose --file /dev/stdin down "${@}"

      if is_sudoer; then
#       sudo sysctl --write fs.inotify.max_user_instances=1024
#       sudo sysctl --write fs.inotify.max_user_watches=65536
        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=53
      fi

      # compose up
      echo "${compose_yml}" | podman-compose --file /dev/stdin up "${@}" & # --detach

      if is_sudoer; then

        # wait
        while [[ 'running' != "$(echo "${compose_yml}" | podman-compose --file /dev/stdin ps --format json | jq -r '.[] | select(.Labels."com.docker.compose.service" == "proxy").State')" ]]; do
          sleep 1
        done

#       sudo sysctl --write fs.inotify.max_user_instances=128
#       sudo sysctl --write fs.inotify.max_user_watches=8192
        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=1024

      fi

      # clean
      podman system  prune --force || true
      podman volume  prune --force || true
      podman network prune --force || true

    else
      tmux display-message -p '#S.#I.#P'
      false
    fi

  popd &> /dev/null
)
