#!/bin/bash
: << 'END_OF_BATCH'
@rem ================================ windows batch [ms932, crlf] ================================
@echo off

setlocal

  cd /d "%USERPROFILE%"

  set dist=debian

  rem clean
::wsl --unregister %dist%
::wsl --set-default-version 2
::wsl --install --distribution %dist%

  rem setup
  wsl --terminate    %dist%
  wsl --set-version  %dist% 2
  wsl --distribution %dist% -- sed -i 's#:/root:#:/mnt/c/Users/%USERNAME%:#' /etc/passwd
  wsl --distribution %dist% -- $^( wslpath -u %~0 ^)
  wsl --terminate    %dist%

endlocal
exit /b
END_OF_BATCH
# ================================ linux shell script [utf8, lf] ================================

set -o errexit
set -o nounset
set -o pipefail

(

  set -a
    source <(cat '/etc/os-release' | sed 's/^/readonly /g')
  set +a

  test 'debian' == "${ID_LIKE:-${ID}}"
  test 'bash'   == "${SHELL##*/}"
  sudo -v -n

  readonly bin_dir="${HOME}/bin"
  readonly dat_dir="${HOME}/dat"
  readonly doc_dir="${HOME}/doc"
  readonly enc_dir="${HOME}/enc"
  readonly lib_dir="${HOME}/lib"
  readonly mnt_dir="${HOME}/mnt"
  readonly opt_dir="${HOME}/opt"
  readonly sbin_dir="${HOME}/sbin"
  readonly src_dir="${HOME}/src"
  readonly tmp_dir="${HOME}/tmp"

  readonly dns_ip='1.1.1.1'
  readonly domain="$(hostname -d)"
  readonly namespace="$(echo "${domain}" | tr '.' $'\n' | tac | paste -s -d '.')"

  readonly github_user='tkyz'

  # phase
  do_setup=
  do_setup_0=
# do_build=
# do_deploy=
# do_setup_desktop=

  # -------------------------------- setup --------------------------------
  if [[ -v do_setup ]]; then

    # dns
    echo "nameserver ${dns_ip}" | sudo tee '/etc/resolv.conf' > '/dev/null'

    # keyboard
    cat << EOS | sudo tee '/etc/default/keyboard' > '/dev/null'
XKBMODEL=pc105
XKBLAYOUT=jp
XKBVARIANT=
XKBOPTIONS=ctrl:nocaps
BACKSPACE=guess
EOS

    # sysctl
#   sudo sysctl --write fs.inotify.max_user_instances=128 #  1024
#   sudo sysctl --write fs.inotify.max_user_watches=8192  # 65536

    # apt
    if :; then

      export DEBIAN_FRONTEND=noninteractive

      # repo
      cat << EOS | sudo tee '/etc/apt/sources.list.d/org.debian.list' > '/dev/null'
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}           main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}           main contrib non-free non-free-firmware
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}-updates   main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}-updates   main contrib non-free non-free-firmware
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
deb     http://security.debian.org/debian-security ${VERSION_CODENAME}-security  main contrib non-free non-free-firmware
deb-src http://security.debian.org/debian-security ${VERSION_CODENAME}-security  main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               testing                       main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               testing                       main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               unstable                      main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               unstable                      main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               experimental                  main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               experimental                  main contrib non-free non-free-firmware
EOS

      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y extrepo curl gnupg2

      # extrepo
      if :; then

        cat << EOS | sudo tee '/etc/extrepo/config.yaml' > '/dev/null'
url: https://extrepo-team.pages.debian.net/extrepo-data
dist: debian
version: trixie
enabled_policies:
  - main
  - contrib
  - non-free
EOS

#       sudo extrepo enable nvidia-cuda
        sudo extrepo enable kubernetes
        sudo extrepo enable openvpn
        sudo extrepo enable virtualbox
        sudo extrepo enable github-cli
        sudo extrepo enable google_cloud
        sudo extrepo enable dotnet
        sudo extrepo enable winehq

      fi

      # nvidia
      #   https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#with-apt-ubuntu-debian
      if :; then

        pub_file='/etc/apt/keyrings/nvidia-container-toolkit.gpg'
        src_file='/etc/apt/sources.list.d/nvidia-container-toolkit.list'

        curl -fsSL 'https://nvidia.github.io/libnvidia-container/gpgkey' | sudo gpg --dearmor | sudo tee "${pub_file}" > '/dev/null'
        cat << EOS | sudo tee "${src_file}" > '/dev/null'
deb  [signed-by=${pub_file}] https://nvidia.github.io/libnvidia-container/stable/deb/\$(ARCH)       /
#deb [signed-by=${pub_file}] https://nvidia.github.io/libnvidia-container/experimental/deb/\$(ARCH) /
EOS

      fi

      sudo apt-get update
      sudo apt-get upgrade -y

      cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty sudo apt-get install -y
# kernel
  linux-headers-$(uname -r | sed 's/.*-//g')

# firmware
  firmware-linux
  firmware-realtek
  firmware-iwlwifi

# trust
  openssl
  gnupg2
  gpgsm

# secure
  ufw
  rkhunter
  clamav

# time
  ntpsec-ntpdate
  faketime

# locale
  locales-all
  task-japanese

# hw
  lshw
  lsscsi
  usbutils

# fs
  parted
  cryptsetup
  lvm2

# fuse
  fuse
  smbclient
  cifs-utils
  gocryptfs
  archivemount

# gpu
  nvidia-driver
  nvidia-container-toolkit
# nvidia-open

# cups
  cups

# pcsc
  opensc
  pcscd
  pcsc-tools
# libpcsclite-dev
# libnfc-bin
# libpam-p11

# shell
  bash
  bash-completion
# zsh
# fish
  tmux

# python
  python3
  python3-pip
  python3-venv

# git
  git
  git-crypt
  git-lfs

# container
  containerd
  podman

# editor
  vim
# emacs

# net
  iproute2
  bind9-dnsutils
  nmap
  curl
  openssh-client
  openssh-server

# k8s
  kubectl
# kubelet
# kubeadm

# cloud
# google-cloud-cli
# awscli

# ...
  uuid-runtime
  rsync
  jq
  qrencode
EOS
    fi

    # ufw
    printf 'y' | sudo ufw reset > '/dev/null'
    sudo ufw default deny  incoming
    sudo ufw default allow outgoing
    sudo ufw enable
    sudo ufw reload

    # rkhunter
    if :; then

      sudo sed -i -r \
        -e 's/^#?LANGUAGE=.*$/LANGUAGE=ja/g' \
        -e 's/^#?UPDATE_LANG=.*$/UPDATE_LANG=ja/g' \
        -e 's/^#?WEB_CMD=.*$/WEB_CMD=""/g' \
        -e 's/^#?UPDATE_MIRRORS=.*$/UPDATE_MIRRORS=1/g' \
        -e 's/^#?MIRRORS_MODE=.*$/MIRRORS_MODE=0/g' \
        -e 's/^#?PKGMGR=.*$/PKGMGR=DPKG/g' \
        '/etc/rkhunter.conf'

      sudo rkhunter --update || true
      sudo rkhunter --propupd
#     sudo rkhunter --versioncheck
#     sudo rkhunter --check --skip-keypress

    fi

    # clamav
    sudo systemctl stop  clamav-freshclam
    sudo freshclam
    sudo systemctl start clamav-freshclam

    # ssh
    sudo sed -i -r \
      -e 's/^#?PermitRootLogin[[:space:]].*$/PermitRootLogin no/g' \
      -e 's/^#?PermitEmptyPasswords[[:space:]].*$/PermitEmptyPasswords no/g' \
      -e 's/^#?PasswordAuthentication[[:space:]].*$/PasswordAuthentication no/g' \
      -e 's/^#?PubkeyAuthentication[[:space:]].*$/PubkeyAuthentication yes/g' \
      -e 's/^#?StrictModes[[:space:]].*$/StrictModes yes/g' \
      -e 's|^#?AuthorizedKeysFile[[:space:]].*$|AuthorizedKeysFile .ssh/authorized_keys|g' \
      '/etc/ssh/sshd_config'
#     -e 's/^#?MaxAuthTries .*$/MaxAuthTries 1/g' \

    # container
    sudo sed -i -r "s/^(# )?unqualified-search-registries = .*/unqualified-search-registries = ['container.${domain}', 'docker.io']/" '/etc/containers/registries.conf'

    # .venv
    python3 -m venv "${HOME}/.venv"
    source "${HOME}/.venv/bin/activate"

    # cups
    #   https://www.brother.co.jp/support/index.aspx
    #   https://canon.jp/support/software
    #   https://www.epson.jp/support/download/

    # pip
    if :; then

      # pytorch
      #   https://pytorch.org/get-started/previous-versions/
      pip install torch==2.6.0  torchvision==0.21.0 torchaudio==2.6.0 --index-url 'https://download.pytorch.org/whl/cu124'
#     pip install torch==2.12.1 torchvision==0.27.1                   --index-url 'https://download.pytorch.org/whl/cu132'

      cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 pip install
# container
  podman
  podman-compose

# util
  yq

# dl
  transformers
EOS

    fi

  fi

  # -------------------------------- 0.git --------------------------------
  if [[ -v do_setup_0 ]]; then

    pushd "${HOME}" &> '/dev/null'

      mkdir -p \
        "${bin_dir}" \
        "${dat_dir}" \
        "${doc_dir}" \
        "${enc_dir}" \
        "${lib_dir}" \
        "${mnt_dir}" \
        "${opt_dir}" \
        "${sbin_dir}" \
        "${src_dir}" \
        "${tmp_dir}"

      git config --global init.defaultBranch main
      git config --global core.ignorecase    false
      git config --global core.quotepath     false
      git config --global core.autocrlf      false
      git config --global core.safecrlf      true
      git config --global core.filemode      true
      git config --global core.symlinks      true
      git config --global core.hooksPath     "${HOME}/.git-hooks"
      git config --global color.ui           auto
      git config --global color.diff         auto
      git config --global color.status       auto
      git config --global color.branch       auto
      git config --global pull.ff            only
      git config --global pull.rebase        true
      git config --global pull.autostash     false
      git config --global rebase.autostash   false
      git config --global merge.ff           false
      git config --global diff.sjis.textconv 'iconv -f sjis'
      git config --global filter.lfs.smudge  'git-lfs smudge --skip -- %f'
      git config --global gpg.program        "$(type -p gpg)"
      git config --global commit.gpgsign     true

#     git init --object-format=sha256 '.'
      git init                        '.'

      # remote
      {
#       git_remote='origin';   git_uri="${lib_dir}/${namespace}.git/0.git";         git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
        git_remote="upstream"; git_uri="git://git.${domain}/0.git";                 git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
        git_remote='public';   git_uri="https://github.com/${github_user}/0.git";   git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
#       git_remote='github';   git_uri="ssh://git@github.com/${github_user}/0.git"; git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
      } 2> '/dev/null'

      git fetch --prune --all || true

      # head
      git remote | while read remote; do
        git remote set-head "${remote}" 'main' || true
      done

      # checkout
      if git checkout --orphan 'main' 2> '/dev/null'; then

        {
          ( git reset --mixed 'origin/main'    && git branch --set-upstream-to='origin/main'   ) ||
          ( git reset --mixed "${domain}/main" && git branch --set-upstream-to="${domain}/main") ||
          ( git reset --mixed 'public/main'    && git branch --set-upstream-to='public/main'   ) ||
          ( git reset --mixed 'github/main'    && git branch --set-upstream-to='github/main'   ) ||
          true
        } 2> '/dev/null'

        git diff --name-only -z --diff-filter=D | xargs -0 git checkout

        cp './.profile' './.profile.bk'; git checkout './.profile'
        cp './.bashrc'  './.bashrc.bk';  git checkout './.bashrc'

        # activate profile
        set +o errexit +o nounset +o pipefail
          source './.profile'
        set -o errexit -o nounset -o pipefail

      fi

      git gc
      git status

    popd &> '/dev/null'

    # myna
    if :; then

      curi 'https://github.com.github/jpki/myna.git'

      podman run --interactive --rm --volume "${src_dir}/com.github/jpki/myna:/build" --workdir '/build' "docker.io/library/rust:${VERSION_CODENAME}" bash << EOS
        apt-get update -y
        apt-get install -y libpcsclite-dev
        cargo build --workspace --release
EOS

    fi

  fi

  # -------------------------------- identifier --------------------------------

  # ⚠️restore
# bkuser "${USER}" '00000000-0000-0000-0000-000000000000' 'restore'

  # identifier
  if :; then

    readonly openpgp4fpr="$(openpgp4fpr)"

    # ⚠️暗号化ペイロード
    if [[ '57965a50fa04846b03788571e43f19d7cf757743a4fa365add1202329982a437' == "$(echo -n "$(machine_id)" | vhash)" ]]; then
#     cat << 'EOS' | enc | base64
      cat << 'EOS' | base64 -d | dec | ( source '/dev/stdin' )
hF4DAAAAAAAAAAASAQdAyzMylrtsuLM37O3VI5L1GbT1PrGv2M37SI0GaVdHfRQwVjCqw9LgFy08
G1NOZxN01IE5T+KGhTxzss7FIQVtOG5bka/rV6PkW1fIK5/haY5o0owBQL+5EH5YmMn4METaZ+QA
5yoLijyipG0jqgtP7wiIr9Hr87Kf71L2V5pgzRcfKDTA6zmqelzizpLVpJn7+/V0BzDM92ToiOks
2rPDLNfpETD7M2605oXRDNMjtSKfkwLN7WmKqG+8JIwyOT4ogENE9icDWGiN1sS4rFRTJ9tiYJpw
tQlf0x+BqPhgmw==
EOS
    fi

    readonly jpki_id="$(jpki_id)"

    readonly machine_id="$(machine_id)"
    readonly boot_id="$(boot_id)"
    readonly setup_id="$(uuidgen)"

    readonly lan_ip="$(ip -4 addr | grep inet | grep 'scope global' | awk -F ' ' '{print $2}' | sed 's|/.*||g' | head -n 1)"
    test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver1.opendns.com')"
    test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver2.opendns.com')"
    test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver3.opendns.com')"
    test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver4.opendns.com')"
    test ! -v wan_ip && readonly wan_ip="$(dig +short txt ch 'whoami.cloudflare'       '@1.1.1.1'        | tr -d '"')"
    test ! -v wan_ip && readonly wan_ip="$(dig +short txt    'o-o.myaddr.l.google.com' '@ns1.google.com' | tr -d '"')"

  fi

  # git
  if :; then

#   uid_line="$(gpg --with-colons --list-keys "${openpgp4fpr}" | awk -F: '/^uid:/ {print $10; exit}')"
#   gpg_user="$(echo "${uid_line}" | sed ...)"
#   gpg_mail="$(echo "${uid_line}" | sed ...)"

#   git config --global user.name       "${gpg_user:-${USER}}"
#   git config --global user.email      "${gpg_mail:-${USER}@$(hostname -f)}"
    git config --global user.signingkey "$(gpg --with-colons --list-keys "0x${openpgp4fpr}" | grep -A 1 :s: | grep ^fpr: | cut -d : -f 10)"

  fi

  # ssh
  if :; then

    onetime_key="/tmp/${setup_id}"
    onetime_pub="${onetime_key}.pub"

#   ssh-keygen -t rsa     -b 4096 -C '' -N '' -f "${onetime_key}"
    ssh-keygen -t ed25519 -a 4096 -C '' -N '' -f "${onetime_key}"

    mkdir -p "${HOME}/.ssh"
    auth_file="${HOME}/.ssh/authorized_keys"
    {
      cat "${onetime_pub}"
      is_myna && myna jpki cert --type auth --format der | openssl x509 -inform der -noout -pubkey | ssh-keygen -f '/dev/stdin' -i -m pkcs8 || true
#     curl -fsSL "https://github.com/${github_user}.keys"
    } | sort -u > "${auth_file}"

    chmod 700 "${HOME}/.ssh"
    chmod 600 "${auth_file}"

    ssh-add -D
    ssh-add "${onetime_key}"

  fi

  # .env
  if :; then

    readonly external_ip="${lan_ip}"

    cat << EOS | tr -d ' ' > "${HOME}/.env"
# uid
openpgp4fpr = ${openpgp4fpr}
jpki_id     = ${jpki_id}

# scope
machine_id  = ${machine_id}
boot_id     = ${boot_id}
setup_id    = ${setup_id}

# network
resolver_ip = ${dns_ip}
external_ip = ${external_ip}
domain      = ${domain}
namespace   = ${namespace}

tag         = latest
EOS

  fi

  # -------------------------------- build --------------------------------
  if [[ -v do_build ]]; then

    # pull
    if :; then

#     cat "${HOME}/lib/list" | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 curi
#     cat "${HOME}/src/list" | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 curi

      podman-compose pull || true

    fi

    # build
    if :; then

      podman run               --rm --volume "${src_dir}/com.github/kubernetes-sigs/kind:/build" --workdir '/build' "docker.io/library/golang:${VERSION_CODENAME}" go build
      podman run               --rm --volume "${src_dir}/com.github/sacloud/usacloud:/build"     --workdir '/build' "docker.io/library/golang:${VERSION_CODENAME}" go build
      podman run               --rm --volume "${src_dir}/com.github/mgdm/htmlq:/build"           --workdir '/build' "docker.io/library/rust:${VERSION_CODENAME}"   cargo build --release
      podman run --interactive --rm --volume "${src_dir}/com.github/jpki/myna:/build"            --workdir '/build' "docker.io/library/rust:${VERSION_CODENAME}"   bash << EOS
      apt-get update -y
      apt-get install -y libpcsclite-dev
      cargo build --workspace --release
EOS

      podman-compose build # --pull --no-cache

    fi

  fi

  # -------------------------------- deploy --------------------------------
  if [[ -v do_deploy ]]; then

    # firewall
    if :; then

      froms=()
#     froms+=('0.0.0.0')
#     froms+=('10.0.0.0/8')
#     froms+=('172.16.0.0/12')
#     froms+=('192.168.0.0/16')
#     froms+=("${lan_ip}")
#     froms+=("${wan_ip}")
      froms+=("${external_ip}")

      for from in "${froms[@]}"; do
        sudo ufw allow from "${from}" to any port   7 proto tcp
        sudo ufw allow from "${from}" to any port   7 proto     udp
        sudo ufw allow from "${from}" to any port  22 proto tcp
        sudo ufw allow from "${from}" to any port  53 proto tcp
        sudo ufw allow from "${from}" to any port  53 proto     udp
        sudo ufw allow from "${from}" to any port  80 proto tcp
        sudo ufw allow from "${from}" to any port 123 proto     udp
        sudo ufw allow from "${from}" to any port 443 proto tcp
      done
      sudo ufw reload

    fi
    sudo ufw status verbose

    # cdi
    sudo nvidia-ctk cdi generate --output='/etc/cdi/nvidia.yaml' 2> '/dev/null' || true

    pushd "${HOME}" &> '/dev/null'

#     podman-compose down

      # port: ~1023
      sudo sysctl --write net.ipv4.ip_unprivileged_port_start=7

        echo "nameserver ${dns_ip}"      | sudo tee '/etc/resolv.conf' > '/dev/null'
          podman-compose up dns &
          sleep 1
        echo "nameserver ${external_ip}" | sudo tee '/etc/resolv.conf' > '/dev/null'

        podman-compose up echo ntp &
        sleep 1

      sudo sysctl --write net.ipv4.ip_unprivileged_port_start=1024
      sudo ntpdate "ntp.${domain}" || true

      # port: 1024~
      podman-compose up git apt container &
      sleep 3
      podman-compose up mariadb pgsql redis mongo chroma &
      sleep 5
      podman-compose up tor btc eth &
      sleep 5
      podman-compose up minecraft &
      sleep 3
      podman-compose up setup doc-php chat &
      sleep 3
      podman-compose up doc &
      sleep 3
      podman-compose up bi comfyui &
      sleep 3

      # port: ~1023
      sudo sysctl --write net.ipv4.ip_unprivileged_port_start=80
        podman-compose up proxy &
        sleep 1
      sudo sysctl --write net.ipv4.ip_unprivileged_port_start=1024

    popd &> '/dev/null'

  fi

  # -------------------------------- desktop --------------------------------
  if [[ -v do_setup_desktop ]]; then

#   sudo tasksel

    cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty sudo apt-get install -y
# desktop
  task-japanese-desktop
# task-japanese-gnome-desktop
# task-japanese-gnome-flashback-desktop
  task-xfce-desktop
# task-kde-desktop
  ibus-mozc

# font
  fonts-dejavu-core
  fonts-vlgothic

# flatpak
  flatpak
  gnome-software-plugin-flatpak
# plasma-discover-backend-flatpak

# wine
  wine
  winetricks

# thumbnail
  webp-pixbuf-loader
  tumbler
  tumbler-plugins-extra
  ffmpegthumbnailer
EOS

    # flatpak
    #   https://flathub.org/ja/setup/Debian
    if :; then

      sudo flatpak remote-add --if-not-exists flathub 'https://dl.flathub.org/repo/flathub.flatpakrepo'

      cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty sudo flatpak install -y flathub
# flathub
  org.telegram.desktop
  com.discordapp.Discord
  org.torproject.torbrowser-launcher
  org.mozilla.firefox
# org.libreoffice.LibreOffice
# org.gimp.GIMP
# com.valvesoftware.Steam
# com.obsproject.Studio
EOS

    fi

    # firefox + mpa
    if :; then

      mpa_file="${HOME}/src/com.github/jpki/myna/target/release/mpa"
      if [[ -f "${mpa_file}" ]]; then

        # manifest
#       exp_dir="${HOME}/.mozilla/native-messaging-hosts"
        exp_dir="${HOME}/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts"
        mkdir -p "${exp_dir}"
        cat << EOS > "${exp_dir}/com.github.jpki.mpa.json"
{
  "name":        "com.github.jpki.mpa",
  "description": "MPA for Linux",
  "path":        "${mpa_file}",
  "type":        "stdio",
  "allowed_extensions": [
    "mpa@${domain}"
  ]
}
EOS

        # config
        exp_dir="${HOME}/.config/mpa"
        mkdir -p "${exp_dir}"
        cat << EOS > "${exp_dir}/config.json"
{"uuid": "$(od -An -tx1 -N16 '/dev/urandom' | tr -d ' \n')"}
EOS

      fi

    fi

    # wine
    if :; then
      winetricks cjkfonts gdiplus
      wine reg add 'HKCU\Control Panel\Desktop' /v 'LogPixels' /t REG_DWORD /d 192 /f
    fi

  fi

  # -------------------------------- ... --------------------------------

  # clean
  if :; then

    sudo apt-get autoremove -y
    sudo apt-get clean

    pip3 cache purge

    podman system  prune --force || true
    podman volume  prune --force || true
    podman network prune --force || true

  fi

  # dat
  if :; then

    # openpgp4fpr
    mkdir -p                                              "${dat_dir}/openpgp4fpr/${openpgp4fpr}"
    gpg --armor --export             "0x${openpgp4fpr}" > "${dat_dir}/openpgp4fpr/${openpgp4fpr}/pub"
#   gpg --armor --export-secret-keys                    > "${HOME}/gpg.0x${openpgp4fpr}.key"

    # lan
#   mkdir -p "${dat_dir}/ipv4/${lan_ip}"
    ip -4 addr | grep inet | grep 'scope global' | awk -F ' ' '{print $2}' | sed 's|/.*||g' | while read i; do
      mkdir -p "${dat_dir}/ipv4/${i}"
    done

    # wan
    mkdir -p "${dat_dir}/ipv4/${wan_ip}"
    mkdir -p "${dat_dir}/wan/$(nslookup "${wan_ip}" | head -n 1 | sed -r 's/^.* ([^ ]+)\.$/\1/g' | tr '.' $'\n' | tac | paste -s -d '.')"

    # doc
    echo -n "http://doc.${domain}/" | qrencode --type 'png' --output "${dat_dir}/logo.png"

    # scope
    mkdir -p \
      "${dat_dir}/machine_id/${machine_id}" \
      "${dat_dir}/boot_id/${boot_id}" \
      "${dat_dir}/setup_id/${setup_id}"

  fi

) >&2
