#!/bin/bash
: << 'END_OF_BATCH'
@rem ================================ windows batch [ms932, crlf] ================================
@echo off

setlocal

  cd /d "%USERPROFILE%"

  set dist=debian

  rem clean
::wsl --unregister %dist%
::wsl --set-default-version 2
::wsl --install --distribution %dist%

  rem setup
  wsl --terminate    %dist%
  wsl --set-version  %dist% 2
  wsl --distribution %dist% -- sed -i 's#:/root:#:/mnt/c/Users/%USERNAME%:#' /etc/passwd
  wsl --distribution %dist% -- $^( wslpath -u %~0 ^)
  wsl --terminate    %dist%

endlocal
exit /b
END_OF_BATCH
# ================================ linux shell script [utf8, lf] ================================

set -o errexit
set -o nounset
set -o pipefail

(

  set -a
    source <(cat '/etc/os-release' | sed 's/^/readonly /g')
  set +a

  test 'debian' == "${ID_LIKE:-${ID}}"
  test 'bash'   == "${SHELL##*/}"
  sudo -v -n

  readonly bin_dir="${HOME}/bin"
  readonly dat_dir="${HOME}/dat"
  readonly doc_dir="${HOME}/doc"
  readonly enc_dir="${HOME}/enc"
  readonly lib_dir="${HOME}/lib"
  readonly mnt_dir="${HOME}/mnt"
  readonly opt_dir="${HOME}/opt"
  readonly sbin_dir="${HOME}/sbin"
  readonly src_dir="${HOME}/src"
  readonly tmp_dir="${HOME}/tmp"

  readonly domain="$(hostname -d)"
  readonly namespace="$(echo "${domain}" | tr '.' $'\n' | tac | paste -s -d '.')"

  readonly dns_ip='1.1.1.1'

  readonly github_user='tkyz'

  # -------------------------------- setup --------------------------------
  if true; then

    # dns
    echo "nameserver ${dns_ip}" | sudo tee '/etc/resolv.conf' > '/dev/null'

    # keyboard
    cat << EOS | sudo tee '/etc/default/keyboard' > '/dev/null'
XKBMODEL=pc105
XKBLAYOUT=jp
XKBVARIANT=
XKBOPTIONS=ctrl:nocaps
BACKSPACE=guess
EOS

    # sysctl
#   sudo sysctl --write fs.inotify.max_user_instances=128 #  1024
#   sudo sysctl --write fs.inotify.max_user_watches=8192  # 65536

    # apt
    if :; then

      export DEBIAN_FRONTEND=noninteractive

      # repo
      cat << EOS | sudo tee '/etc/apt/sources.list.d/org.debian.list' > '/dev/null'
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}           main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}           main contrib non-free non-free-firmware
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}-updates   main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}-updates   main contrib non-free non-free-firmware
deb     http://deb.debian.org/debian               ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian               ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware
deb     http://security.debian.org/debian-security ${VERSION_CODENAME}-security  main contrib non-free non-free-firmware
deb-src http://security.debian.org/debian-security ${VERSION_CODENAME}-security  main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               testing                       main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               testing                       main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               unstable                      main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               unstable                      main contrib non-free non-free-firmware
#deb     http://deb.debian.org/debian               experimental                  main contrib non-free non-free-firmware
#deb-src http://deb.debian.org/debian               experimental                  main contrib non-free non-free-firmware
EOS

      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y extrepo curl gnupg2

      # extrepo
      cat << EOS | sudo tee '/etc/extrepo/config.yaml' > '/dev/null'
url: https://extrepo-team.pages.debian.net/extrepo-data
dist: debian
version: trixie
enabled_policies:
  - main
  - contrib
  - non-free
EOS
#     sudo extrepo enable nvidia-cuda
      sudo extrepo enable kubernetes
      sudo extrepo enable openvpn
      sudo extrepo enable virtualbox
      sudo extrepo enable github-cli
      sudo extrepo enable google_cloud
      sudo extrepo enable dotnet
      sudo extrepo enable winehq

      # nvidia
      #   https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#with-apt-ubuntu-debian
      if :; then
        pub_file='/etc/apt/keyrings/nvidia-container-toolkit.gpg'
        src_file='/etc/apt/sources.list.d/nvidia-container-toolkit.list'
        curl -fsSL 'https://nvidia.github.io/libnvidia-container/gpgkey' | sudo gpg --dearmor | sudo tee "${pub_file}" > '/dev/null'
        cat << EOS | sudo tee "${src_file}" > '/dev/null'
deb  [signed-by=${pub_file}] https://nvidia.github.io/libnvidia-container/stable/deb/\$(ARCH)       /
#deb [signed-by=${pub_file}] https://nvidia.github.io/libnvidia-container/experimental/deb/\$(ARCH) /
EOS
      fi

      sudo apt-get update
      sudo apt-get upgrade -y

      cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty sudo apt-get install -y
# kernel
  linux-headers-$(uname -r | sed 's/.*-//g')

# firmware
  firmware-linux
  firmware-realtek
  firmware-iwlwifi

# trust
  openssl
  gnupg2
  gpgsm

# secure
  ufw
  rkhunter
  clamav

# time
  ntpsec-ntpdate
  faketime

# locale
  locales-all
  task-japanese
# fonts-dejavu-core

# hw
  lshw
  lsscsi
  usbutils

# fs
  parted
  cryptsetup
  lvm2

# fuse
  fuse
  smbclient
  cifs-utils
  gocryptfs
  archivemount

# gpu
  nvidia-driver
  nvidia-container-toolkit
# nvidia-open

# cups
  cups

# pcsc
  opensc
  pcscd
  pcsc-tools
# libpcsclite-dev
# libnfc-bin
# libpam-p11

# shell
  bash
  bash-completion
# zsh
# fish
  tmux

# python
  python3
  python3-pip
  python3-venv

# git
  git
  git-crypt
  git-lfs

# container
  containerd
  podman

# editor
  vim
# emacs

# net
  iproute2
  bind9-dnsutils
  nmap
  curl
  openssh-client
  openssh-server

# k8s
  kubectl
# kubelet
# kubeadm

# cloud
# google-cloud-cli
# awscli

# ...
  uuid-runtime
  rsync
  jq
  qrencode
EOS
    fi

    # ufw
    printf 'y' | sudo ufw reset > '/dev/null'
    sudo ufw default deny  incoming
    sudo ufw default allow outgoing
    sudo ufw enable
    sudo ufw reload

    # rkhunter
    if :; then

      sudo sed -i -r \
        -e 's/^#?LANGUAGE=.*$/LANGUAGE=ja/g' \
        -e 's/^#?UPDATE_LANG=.*$/UPDATE_LANG=ja/g' \
        -e 's/^#?WEB_CMD=.*$/WEB_CMD=""/g' \
        -e 's/^#?UPDATE_MIRRORS=.*$/UPDATE_MIRRORS=1/g' \
        -e 's/^#?MIRRORS_MODE=.*$/MIRRORS_MODE=0/g' \
        -e 's/^#?PKGMGR=.*$/PKGMGR=DPKG/g' \
        '/etc/rkhunter.conf'

      sudo rkhunter --update || true
      sudo rkhunter --propupd
#     sudo rkhunter --versioncheck
#     sudo rkhunter --check --skip-keypress

    fi

    # clamav
    sudo systemctl stop  clamav-freshclam
    sudo freshclam
    sudo systemctl start clamav-freshclam

    # ssh
    sudo sed -i -r \
      -e 's/^#?PermitRootLogin[[:space:]].*$/PermitRootLogin no/g' \
      -e 's/^#?PermitEmptyPasswords[[:space:]].*$/PermitEmptyPasswords no/g' \
      -e 's/^#?PasswordAuthentication[[:space:]].*$/PasswordAuthentication no/g' \
      -e 's/^#?PubkeyAuthentication[[:space:]].*$/PubkeyAuthentication yes/g' \
      -e 's/^#?StrictModes[[:space:]].*$/StrictModes yes/g' \
      -e 's|^#?AuthorizedKeysFile[[:space:]].*$|AuthorizedKeysFile .ssh/authorized_keys|g' \
      '/etc/ssh/sshd_config'
#     -e 's/^#?MaxAuthTries .*$/MaxAuthTries 1/g' \

    # container
    sudo sed -i -r "s/^(# )?unqualified-search-registries = .*/unqualified-search-registries = ['container.${domain}', 'docker.io']/" '/etc/containers/registries.conf'

    # .venv
    python3 -m venv "${HOME}/.venv"
    source "${HOME}/.venv/bin/activate"

    # pip
    if :; then

      # pytorch
      #   https://pytorch.org/get-started/previous-versions/
      pip install torch==2.6.0  torchvision==0.21.0 torchaudio==2.6.0 --index-url 'https://download.pytorch.org/whl/cu124'
#     pip install torch==2.12.1 torchvision==0.27.1                   --index-url 'https://download.pytorch.org/whl/cu132'

      cat << EOS | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 pip install
# container
  podman
  podman-compose

# util
  yq
EOS

    fi

    # cups
    #   https://www.brother.co.jp/support/index.aspx
    #   https://canon.jp/support/software
    #   https://www.epson.jp/support/download/

    # 0.git
    pushd "${HOME}" &> '/dev/null'

      mkdir -p \
        "${bin_dir}" \
        "${dat_dir}" \
        "${doc_dir}" \
        "${enc_dir}" \
        "${lib_dir}" \
        "${mnt_dir}" \
        "${opt_dir}" \
        "${sbin_dir}" \
        "${src_dir}" \
        "${tmp_dir}"

      git config --global init.defaultBranch main
      git config --global core.ignorecase    false
      git config --global core.quotepath     false
      git config --global core.autocrlf      false
      git config --global core.safecrlf      true
      git config --global core.filemode      true
      git config --global core.symlinks      true
      git config --global core.hooksPath     "${HOME}/.git-hooks"
      git config --global color.ui           auto
      git config --global color.diff         auto
      git config --global color.status       auto
      git config --global color.branch       auto
      git config --global pull.ff            only
      git config --global pull.rebase        true
      git config --global pull.autostash     false
      git config --global rebase.autostash   false
      git config --global merge.ff           false
      git config --global diff.sjis.textconv 'iconv -f sjis'
      git config --global filter.lfs.smudge  'git-lfs smudge --skip -- %f'
      git config --global gpg.program        "$(type -p gpg)"
      git config --global commit.gpgsign     true

#     git init --object-format=sha256 '.'
      git init                        '.'

      # remote
      {
#       git_remote='origin';   git_uri="${lib_dir}/${namespace}.git/0.git";         git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
        git_remote="upstream"; git_uri="git://git.${domain}/0.git";                 git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
        git_remote='public';   git_uri="https://github.com/${github_user}/0.git";   git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
#       git_remote='github';   git_uri="ssh://git@github.com/${github_user}/0.git"; git remote add "${git_remote}" "${git_uri}" || git remote set-url "${git_remote}" "${git_uri}" || true
      } 2> '/dev/null'

      git fetch --prune --all || true

      # head
      git remote | while read remote; do
        git remote set-head "${remote}" 'main' || true
      done

      # checkout
      if git checkout --orphan 'main' 2> '/dev/null'; then

        {
          ( git reset --mixed 'origin/main'    && git branch --set-upstream-to='origin/main'   ) ||
          ( git reset --mixed "${domain}/main" && git branch --set-upstream-to="${domain}/main") ||
          ( git reset --mixed 'public/main'    && git branch --set-upstream-to='public/main'   ) ||
          ( git reset --mixed 'github/main'    && git branch --set-upstream-to='github/main'   ) ||
          true
        } 2> '/dev/null'

        git diff --name-only -z --diff-filter=D | xargs -0 git checkout

        cp './.profile' './.profile.bk'; git checkout './.profile'
        cp './.bashrc'  './.bashrc.bk';  git checkout './.bashrc'

        # activate profile
        set +o errexit +o nounset +o pipefail
          source './.profile'
        set -o errexit -o nounset -o pipefail

      fi

      git gc
      git status

    popd &> '/dev/null'

    # cli
    if :; then

      # pull
      cat << EOS | xargs --no-run-if-empty -n 1 curi
https://github.com/kubernetes-sigs/kind.git
https://github.com.github/sacloud/usacloud.git
https://github.com.github/mgdm/htmlq.git
https://github.com.github/jpki/myna.git
EOS

      # build
      podman run               --rm --volume "${src_dir}/com.github/kubernetes-sigs/kind:/build" --workdir '/build' "docker.io/library/golang:${VERSION_CODENAME}" go build
      podman run               --rm --volume "${src_dir}/com.github/sacloud/usacloud:/build"     --workdir '/build' "docker.io/library/golang:${VERSION_CODENAME}" go build
      podman run               --rm --volume "${src_dir}/com.github/mgdm/htmlq:/build"           --workdir '/build' "docker.io/library/rust:${VERSION_CODENAME}"   cargo build --release
      podman run --interactive --rm --volume "${src_dir}/com.github/jpki/myna:/build"            --workdir '/build' "docker.io/library/rust:${VERSION_CODENAME}"   bash << EOS
        apt-get update -y
        apt-get install -y libpcsclite-dev
        cargo build --workspace --release
EOS

    fi

    # clean
    if :; then

      sudo apt-get autoremove -y
      sudo apt-get clean

      pip3 cache purge

      podman system  prune --force || true
      podman volume  prune --force || true
      podman network prune --force || true

    fi

    echo 'reboot'
    false # sudo shutdown -r now;

  # -------------------------------- ⚠️restore --------------------------------
  elif false; then

    user="${USER}"
    uuid='00000000-0000-0000-0000-000000000000'

    bkuser "${user}" "${uuid}" 'restore'

    echo 'relogin'; false
#   exec bash -l

  # -------------------------------- domain --------------------------------
  else

    # identifier
    if :; then

      readonly openpgp4fpr="$(openpgp4fpr)"

      # ⚠️暗号化ペイロード
      if [[ 'a1c69acb35cdaa3582487fa3d57614cb262ee8ae01e0ba4edd2fba0c350db3ec' == "$(echo -n "$(machine_id)" | vhash)" ]]; then
#       cat << 'EOS' | enc | base64
        cat << 'EOS' | base64 -d | dec | ( source '/dev/stdin' )
hF4DAAAAAAAAAAASAQdAUuHoREgu0HmP1lXrMtZCJw6o9qdWAzhZ5Je/TRtHRRIwXXOcIY/eSkEI
u6vAen4CgZm6AstQRDoRtXrdP31EjKaho95p3Hgm7l5NRzM6uWyi0sBvAYqNGiBlBugvbej73GU6
R8GcRFatfDmnQhkLLbai8sYOgvN0JZ1+DtGYc2+ie38CvIO2aQGVIMrPwD8uIpcm3Xj4j6qWskVS
WSg4wfMSQIVQtV98Ng/S/gCyrgI8aQcId1NWTnHuWLsqrEKHoFiwgeIFINyiqOH4lM9AY7SXlJFh
w3FuVvXqepQ8LO3BDA0rGb4q0md4mTJl4f5uU35SBgXiHZ1wOOxejbp2e1i6yUCVZ8061azfrLLE
VoievrMhSYiZHsMPS0TLM6wOvH4Xy0rs1WabnF9DvtoY/HWxkZBV7T/VKpjV5VauhS9jD02yRkEy
iOdY1gKO9aU44BK6U9aL9OqBsjbrlrsiBJ8jEd8Mzb0SHSeEfrnOSjvmetKQWE5SqMCpeGDv+1eN
S0qt
EOS
      fi

      readonly jpki_id="$(jpki_id)"

      readonly machine_id="$(machine_id)"
      readonly boot_id="$(boot_id)"
      readonly setup_id="$(uuidgen)"

      readonly lan_ip="$(ip -4 addr | grep inet | grep 'scope global' | awk -F ' ' '{print $2}' | sed 's|/.*||g' | head -n 1)"
      test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver1.opendns.com')"
      test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver2.opendns.com')"
      test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver3.opendns.com')"
      test ! -v wan_ip && readonly wan_ip="$(dig +short        'myip.opendns.com'        '@resolver4.opendns.com')"
      test ! -v wan_ip && readonly wan_ip="$(dig +short txt ch 'whoami.cloudflare'       '@1.1.1.1'        | tr -d '"')"
      test ! -v wan_ip && readonly wan_ip="$(dig +short txt    'o-o.myaddr.l.google.com' '@ns1.google.com' | tr -d '"')"
      readonly external_ip="${lan_ip}"

    fi

    # ssh
    if :; then

      onetime_key="/tmp/${setup_id}"
      onetime_pub="${onetime_key}.pub"

#     ssh-keygen -t rsa     -b 4096 -C '' -N '' -f "${onetime_key}"
      ssh-keygen -t ed25519 -a 4096 -C '' -N '' -f "${onetime_key}"

      mkdir -p "${HOME}/.ssh"
      auth_file="${HOME}/.ssh/authorized_keys"
      {
        cat "${onetime_pub}"
        cat "${dat_dir}/jpki_id/${jpki_id}/auth.ssh.pub" || true
#       curl -fsSL "https://github.com/${github_user}.keys"
      } | sort -u > "${auth_file}"

      chmod 700 "${HOME}/.ssh"
      chmod 600 "${auth_file}"

      ssh-add -D
      ssh-add "${onetime_key}"

    fi

    # .env
    cat << EOS | tr -d ' ' > "${HOME}/.env"
# uid
openpgp4fpr = ${openpgp4fpr}
jpki_id     = ${jpki_id}

# scope
machine_id  = ${machine_id}
boot_id     = ${boot_id}
setup_id    = ${setup_id}

# network
resolver_ip = ${dns_ip}
external_ip = ${external_ip}
domain      = ${domain}
namespace   = ${namespace}

tag         = latest
EOS

    # dat
    if :; then

      # openpgp4fpr
      if :; then

        mkdir -p                                              "${dat_dir}/openpgp4fpr/${openpgp4fpr}"
        gpg --armor --export             "0x${openpgp4fpr}" > "${dat_dir}/openpgp4fpr/${openpgp4fpr}/pub"
#       gpg --armor --export-secret-keys                    > "${HOME}/gpg.0x${openpgp4fpr}.key"

#       uid_line="$(gpg --with-colons --list-keys "${openpgp4fpr}" | awk -F: '/^uid:/ {print $10; exit}')"
#       gpg_user="$(echo "${uid_line}" | sed ...)"
#       gpg_mail="$(echo "${uid_line}" | sed ...)"

        # git
#       git config --global user.name       "${USER}"
#       git config --global user.email      "${USER}@$(hostname -f)"
        git config --global user.signingkey "$(gpg --with-colons --list-keys "0x${openpgp4fpr}" | grep -A 1 :s: | grep ^fpr: | cut -d : -f 10)"

      fi

      # lan
#     mkdir -p "${dat_dir}/ipv4/${lan_ip}"
      ip -4 addr | grep inet | grep 'scope global' | awk -F ' ' '{print $2}' | sed 's|/.*||g' | while read i; do
        mkdir -p "${dat_dir}/ipv4/${i}"
      done

      # wan
      mkdir -p "${dat_dir}/ipv4/${wan_ip}"
      mkdir -p "${dat_dir}/wan/$(nslookup "${wan_ip}" | head -n 1 | sed -r 's/^.* ([^ ]+)\.$/\1/g' | tr '.' $'\n' | tac | paste -s -d '.')"

      # scope
      mkdir -p \
        "${dat_dir}/machine_id/${machine_id}" \
        "${dat_dir}/boot_id/${boot_id}" \
        "${dat_dir}/setup_id/${setup_id}"

      # qr
      echo -n "http://doc.${domain}/" | qrencode --type 'png' --output "${dat_dir}/logo.png"

    fi

    # cdi
    sudo nvidia-ctk cdi generate --output='/etc/cdi/nvidia.yaml' 2> '/dev/null' || true

    # firewall
    if :; then

      froms=()
#     froms+=('0.0.0.0')
#     froms+=('10.0.0.0/8')
#     froms+=('172.16.0.0/12')
#     froms+=('192.168.0.0/16')
      froms+=("${lan_ip}")
#     froms+=("${wan_ip}")

      for from in "${froms[@]}"; do
        sudo ufw allow from "${from}" to any port   7 proto tcp
        sudo ufw allow from "${from}" to any port   7 proto     udp
        sudo ufw allow from "${from}" to any port  22 proto tcp
        sudo ufw allow from "${from}" to any port  53 proto tcp
        sudo ufw allow from "${from}" to any port  53 proto     udp
        sudo ufw allow from "${from}" to any port  80 proto tcp
        sudo ufw allow from "${from}" to any port 123 proto     udp
        sudo ufw allow from "${from}" to any port 443 proto tcp
      done
      sudo ufw reload

    fi
    sudo ufw status verbose

    pushd "${HOME}" &> '/dev/null'

      # pull
#     cat "${HOME}/lib/list" | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 curi
#     cat "${HOME}/src/list" | sed 's/#.*//g' | xargs --no-run-if-empty -n 1 curi
#     podman-compose pull || true

      # build
      podman-compose build

      # deploy
      if :; then

        podman-compose down

        # port: ~1023
        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=7

          echo "nameserver ${dns_ip}"      | sudo tee '/etc/resolv.conf' > '/dev/null'
            podman-compose up dns &
            sleep 1
          echo "nameserver ${external_ip}" | sudo tee '/etc/resolv.conf' > '/dev/null'

          podman-compose up echo ntp &
          sleep 1

        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=1024
        sudo ntpdate "ntp.${domain}" || true

        # port: 1024~
        podman-compose up git apt container &
        sleep 3
        podman-compose up mariadb pgsql redis mongo chroma &
        sleep 5
        podman-compose up tor btc eth &
        sleep 5
        podman-compose up minecraft &
        sleep 3
        podman-compose up setup doc-php chat &
        sleep 3
        podman-compose up doc &
        sleep 3
        podman-compose up bi comfyui &
        sleep 3

        # port: ~1023
        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=80
          podman-compose up proxy &
          sleep 1
        sudo sysctl --write net.ipv4.ip_unprivileged_port_start=1024

      fi

    popd &> '/dev/null'

  fi

) >&2
