---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "0"
  name: dns
data:
  Corefile: |
    .:53 {
      errors
      ready
      health
      hosts {
        ${external_ip}       dns.0       dns.${tld}
        ${external_ip}       ntp.0       ntp.${tld}
        ${external_ip}       git.0       git.${tld}
        ${external_ip} container.0 container.${tld}
        ${external_ip}       apt.0       apt.${tld}
        ${external_ip}       mvn.0       mvn.${tld}
        ${external_ip}     pgsql.0     pgsql.${tld}
        ${external_ip}     mysql.0     mysql.${tld}
        ${external_ip}   mariadb.0   mariadb.${tld}
        ${external_ip}     redis.0     redis.${tld}
        ${external_ip}      wiki.0      wiki.${tld}
        ${external_ip}       pub.0       pub.${tld}
        ${external_ip} minecraft.0 minecraft.${tld}
        ${external_ip}       btc.0       btc.${tld}
        ${external_ip}       eth.0       eth.${tld}
        ${external_ip}       ltc.0       ltc.${tld}
        fallthrough
      }
      forward . ${resolve}
      loop
      reload
      loadbalance
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "0"
  name: dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: dns
      containers:
        - name: dns
          image: coredns/coredns:latest
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: UDP, containerPort: 53}
          volumeMounts:
            - {name: config-volume, mountPath: /etc/coredns, readOnly: true}
          args: [-conf, /etc/coredns/Corefile]

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: dns
spec:
  type: LoadBalancer
  selector:
    app: dns
  ports:
    - {protocol: UDP, port: 53, nodePort: 53}
