---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${hostname}
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - {name: data-volume, hostPath: {path: /root/lib/0.redis, type: Directory}}
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 6379}
          volumeMounts:
            - {name: data-volume, mountPath: /data}

---
apiVersion: v1
kind: Service
metadata:
  namespace: ${hostname}
  name: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - {protocol: TCP, port: 6379, nodePort: 6379}
