---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setup
  template:
    metadata:
      labels:
        app: setup
    spec:
      volumes:
        - {name: setup,        hostPath: {path: /root/setup}}
        - {name: nginx-volume, hostPath: {path: /root/src/0.setup/nginx/conf, type: Directory}}
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 80}
          volumeMounts:
            - {name: setup,                               mountPath: /usr/share/nginx/html/setup,    readOnly: true}
            - {name: nginx-volume, subPath: nginx.conf,   mountPath: /etc/nginx/nginx.conf,          readOnly: true}
            - {name: nginx-volume, subPath: default.conf, mountPath: /etc/nginx/conf.d/default.conf, readOnly: true}

---
apiVersion: v1
kind: Service
metadata:
  namespace: ${namespace}
  name: setup
spec:
  selector:
    app: setup
  ports:
    - {protocol: TCP, port: 80}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${namespace}
  name: setup
spec:
  rules:
    - host: setup.${domain}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: setup
                port:
                  number: 80
