#!/bin/sh

#----------------------------------------------------------------
# path

if [ "$(id -u)" -eq 0 ]; then
  PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
else
  PATH='/usr/local/bin:/usr/bin:/bin'
fi
export PATH

#----------------------------------------------------------------
# profile.d

if [ -d /etc/profile.d ]; then

  for i in /etc/profile.d/*.sh; do

    if [ ! -r "${i}" ]; then
      continue
    fi
    if [ '0.sh' -eq "${i##*/}" ]; then
      continue
    fi

    . "${i}"

  done
  unset i

fi

if [ -f "${HOME}/etc/profile.d/0.sh" ]; then
  . "${HOME}/etc/profile.d/0.sh"
fi

#----------------------------------------------------------------
# bashrc

if [ -f /etc/bash.bashrc ] && [ "${BASH-}" ] && [ "${BASH}" == '/bin/bash' ]; then
  . /etc/bash.bashrc
fi
