#!/bin/sh

#----------------------------------------------------------------
# path
if [ "$(id -u)" -eq 0 ]; then
  PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
else
  PATH='/usr/local/bin:/usr/bin:/bin'
fi
export PATH

#----------------------------------------------------------------
# profile.d

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

# TODO: 重複呼び出し
if [ -d "${HOME}/etc/profile.d" ]; then
  for i in "${HOME}"/etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

#----------------------------------------------------------------
# bashrc
if [ -f /etc/bash.bashrc ] && [ "${BASH-}" ] && [ "${BASH}" == '/bin/bash' ]; then
  . /etc/bash.bashrc
fi
