---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "0"
  name: bigtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigtop
  template:
    metadata:
      labels:
        app: bigtop
    spec:
      volumes:
        - {name: ssh-volume,  hostPath: {path: /root/.ssh,        type: Directory}}
        - {name: data-volume, hostPath: {path: /var/lib/0.bigtop, type: Directory}}
#       - {name: log-volume,  hostPath: {path: /var/log/0.bigtop, type: Directory}}
      containers:
        - name: bigtop
          image: "container.0/0.bigtop:${build_context}"
          imagePullPolicy: IfNotPresent
          ports:
#           - {protocol: TCP, containerPort:    22}
            - {protocol: TCP, containerPort:  2181}
            - {protocol: TCP, containerPort:  8020}
#           - {protocol: TCP, containerPort:  9870}
          volumeMounts:
            - {name: ssh-volume,  mountPath: /root/.ssh, readOnly: true}
            - {name: data-volume, mountPath: /var/lib/bigtop}
            - {name: data-volume, mountPath: /var/lib/hadoop-hdfs}
            - {name: data-volume, mountPath: /var/lib/hadoop-mapreduce}
            - {name: data-volume, mountPath: /var/lib/hadoop-yarn}
            - {name: data-volume, mountPath: /var/lib/hbase}
            - {name: data-volume, mountPath: /var/lib/hive}
            - {name: data-volume, mountPath: /var/lib/hive-hcatalog}
            - {name: data-volume, mountPath: /var/lib/kafka}
            - {name: data-volume, mountPath: /var/lib/spark}
            - {name: data-volume, mountPath: /var/lib/zookeeper}
#           - {name: log-volume,  mountPath: /var/log}

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: zookeeper
spec:
  type: LoadBalancer
  selector:
    app: bigtop
  ports:
    - {protocol: TCP, port: 2181, nodePort: 2181}

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: hdfs
spec:
  type: LoadBalancer
  selector:
    app: bigtop
  ports:
    - {protocol: TCP, port: 8020, nodePort: 8020}
