---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "0"
  name: doc
data:
  default.conf: |
    server {
      listen 80;
    # listen 443 ssl;
      server_name _;
      root /usr/share/nginx/html;
      index doku.php index.php;
      location ~ /(data|conf|bin|inc|vendor)/ {
        deny all;
      }
      location / {
        try_files $uri $uri/ @dokuwiki;
      }
      location @dokuwiki {
        rewrite ^/_media/(.*)          /lib/exe/fetch.php?media=$1  last;
        rewrite ^/_detail/(.*)         /lib/exe/detail.php?media=$1 last;
        rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
        rewrite ^/(?!lib/)(.*)         /doku.php?id=$1&$args        last;
      }
      location ~ \.php$ {
        if (!-f $request_filename) {
          return 404;
        }
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REDIRECT_STATUS 200;
        fastcgi_pass  localhost:9000;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "0"
  name: doc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      volumes:
        - {name: nginx-volume,    configMap: {name: doc}}
        - {name: dokuwiki-volume, hostPath:  {path: /mnt/0.doc/dokuwiki, type: Directory}}
        - {name: pub-volume,      hostPath:  {path: /mnt/0.pub,          type: Directory}}
        - {name: github-volume,   hostPath:  {path: /mnt/com.github,     type: Directory}}
        - {name: gitlab-volume,   hostPath:  {path: /mnt/com.gitlab,     type: Directory}}
      containers:
        - name: phpfpm
          image: container.0/net.php/fpm:${context}
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 9000}
          volumeMounts:
            - {name: github-volume,   subPath: splitbrain/dokuwiki,                     mountPath: /usr/share/nginx/html}
            - {name: github-volume,   subPath: Chris--S/dokuwiki-plugin-iframe,         mountPath: /usr/share/nginx/html/lib/plugins/iframe}
            - {name: github-volume,   subPath: Chris--S/dokuwiki-plugin-xbr,            mountPath: /usr/share/nginx/html/lib/plugins/xbr}
            - {name: github-volume,   subPath: lejmr/dokuwiki-plugin-drawio,            mountPath: /usr/share/nginx/html/lib/plugins/drawio}
            - {name: github-volume,   subPath: selfthinker/dokuwiki_plugin_wrap,        mountPath: /usr/share/nginx/html/lib/plugins/wrap}
            - {name: github-volume,   subPath: splitbrain/dokuwiki-plugin-translation,  mountPath: /usr/share/nginx/html/lib/plugins/translation}
            - {name: github-volume,   subPath: hanche/dokuwiki_color_plugin,            mountPath: /usr/share/nginx/html/lib/plugins/color}
            - {name: github-volume,   subPath: samuelet/indexmenu,                      mountPath: /usr/share/nginx/html/lib/plugins/indexmenu}
            - {name: gitlab-volume,   subPath: MatthiasLohr/dokuwiki-barcodes,          mountPath: /usr/share/nginx/html/lib/plugins/barcodes}
            - {name: github-volume,   subPath: giterlizzi/dokuwiki-template-bootstrap3, mountPath: /usr/share/nginx/html/lib/tpl/bootstrap3}
            - {name: dokuwiki-volume, subPath: conf,                                    mountPath: /usr/share/nginx/html/conf}
            - {name: dokuwiki-volume, subPath: data,                                    mountPath: /usr/share/nginx/html/data/pages}
            - {name: dokuwiki-volume, subPath: data,                                    mountPath: /usr/share/nginx/html/data/media}
            - {name: pub-volume,                                                        mountPath: /usr/share/nginx/html/data/pages/0.pub}
            - {name: pub-volume,                                                        mountPath: /usr/share/nginx/html/data/media/0.pub}
          command: [/bin/sh, -c]
          args:
            - |
              #find /usr/share/nginx/html -type d -print0 | xargs -0 chmod 777
              #find /usr/share/nginx/html -type f -print0 | xargs -0 chmod 666
              php-fpm
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 80}
          volumeMounts:
            - {name: nginx-volume,                                                      mountPath: /etc/nginx/conf.d,                        readOnly: true}
            - {name: github-volume,   subPath: splitbrain/dokuwiki,                     mountPath: /usr/share/nginx/html,                    readOnly: true}
            - {name: github-volume,   subPath: giterlizzi/dokuwiki-template-bootstrap3, mountPath: /usr/share/nginx/html/lib/tpl/bootstrap3, readOnly: true}

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: doc
spec:
  type: LoadBalancer
  selector:
    app: doc
  ports:
    - {protocol: TCP, port: 80}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "0"
  name: doc
spec:
  rules:
    - host: doc.0
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: doc
                port:
                  number: 80
    - host: doc.${tld}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: doc
                port:
                  number: 80
