#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [[ -v RTORRENT_PORT ]]; then
  sed -ri -e "s/(network.port_range.set).*/\1 = ${RTORRENT_PORT}-${RTORRENT_PORT}/g" /root/.rtorrent.rc
fi

rtorrent "${@}"
