#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

version=${1:-0}

#----------------------------------------------------------------
# mvn
if [[ -f ./pom.xml ]]; then

  if ! is_container && ! is_wsl; then

    workdir="/tmp/$(uuidgen)"

    docker run \
      --interactive \
      --tty \
      --rm \
      --network host \
      --volume "${HOME}/.bin:/usr/local/bin:ro" \
      --volume "${HOME}/.m2:/root/.m2:ro" \
      --volume "${HOME}/lib:/root/lib" \
      --volume "${HOME}/opt/net.java.jdk:/root/opt/net.java.jdk:ro" \
      --volume "${HOME}/opt/org.apache.maven:/root/opt/org.apache.maven:ro" \
      --volume "${HOME}/var/org.apache.maven:/root/var/org.apache.maven" \
      --volume "${PWD}:${workdir}" \
      --workdir "${workdir}" \
      debian:latest bash -c "
        build "${@}"
        chown -R $(id -u):$(id -g) .
      "

#     --name "build_$(date '+%Y%m%d_%H%M%S')" \

  else

    export MAVEN_OPTS='-Xms256m -Xmx256m -XX:-UsePerfData'

    define=()
    defune+=("--define" "version=${version}")
    if ! grep -q '<packaging>pom</packaging>' ./pom.xml; then
      defune+=("--define" "checkstyle.skip=false")
      defune+=("--define" "maven.test.skip=false")
      defune+=("--define" "maven.javadoc.skip=false")
      defune+=("--define" "assembly.skipAssembly=false")
    fi

    mvn \
      --threads 1C \
      "${defune[@]}" \
      clean \
      package \
      install

    # executable-jar
    suffix='-jar-with-dependencies.jar'
    jarwithdeps="$(find target -mindepth 1 -maxdepth 1 -type f -name "*${suffix}" 2> /dev/null || true)"
    jarwithexec="$(echo "${jarwithdeps}" | sed "s/${suffix}//")"
    if [[ -n "${jarwithdeps}" ]]; then

      cat \
        '/usr/local/bin/executable-jar-header-bat' \
        '/usr/local/bin/executable-jar-header-sh'  \
        '/usr/local/bin/executable-jar-header-jar' \
        "${jarwithdeps}" > "${jarwithexec}"

      chmod +x "${jarwithexec}"

    fi

  fi

fi
