#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if true; then

  source /etc/os-release
  test 'debian' == "${ID}"

  readonly arch="$(dpkg --print-architecture)"

fi

#----------------------------------------------------------------
# apt

apt_pkgs=()
pip_pkgs=()
npm_pkgs=()
declare -A opts

# apt repository
if true; then

  curl -fsSL "https://download.docker.com/linux/${ID}/gpg"           | gpg --dearmor --output '/etc/apt/trusted.gpg.d/com.docker.download.gpg'
  curl -fsSL 'https://packages.cloud.google.com/apt/doc/apt-key.gpg' | gpg --dearmor --output '/etc/apt/trusted.gpg.d/com.google.cloud.packages.gpg'
  curl -fsSL 'https://bazel.build/bazel-release.pub.gpg'             | gpg --dearmor --output '/etc/apt/trusted.gpg.d/build.bazel.gpg'

  echo "deb [arch=${arch}] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" | tee    '/etc/apt/sources.list.d/com.docker.download.list'
  echo 'deb https://packages.cloud.google.com/apt cloud-sdk       main'                        | tee    '/etc/apt/sources.list.d/com.google.cloud.packages.list'
  echo 'deb https://packages.cloud.google.com/apt gcsfuse-stretch main'                        | tee -a '/etc/apt/sources.list.d/com.google.cloud.packages.list'
  echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main'                                  | tee    '/etc/apt/sources.list.d/io.kubernetes.apt.list'
  echo "deb [arch=${arch}] http://storage.googleapis.com/bazel-apt stable jdk1.8"              | tee    '/etc/apt/sources.list.d/build.bazel.list'

  apt update || true

fi

if true; then

  apt_pkgs+=('openssh-client')
  apt_pkgs+=('tcpdump')
  apt_pkgs+=('nmap')
  apt_pkgs+=('dnsutils')
  apt_pkgs+=('netcat')
  apt_pkgs+=('cifs-utils')
  apt_pkgs+=('nfs-common')
  apt_pkgs+=('sshfs')
  apt_pkgs+=('rsync')
  apt_pkgs+=('wget')

fi

if ! is_docker_build && ! is_wsl; then

  apt_pkgs+=('ufw')
  apt_pkgs+=('rkhunter')
  apt_pkgs+=('clamav')

fi

if ! is_wsl; then
  apt_pkgs+=("linux-headers-$(uname --kernel-release)")
fi
if is_docker_build || is_wsl; then

  apt_pkgs+=('libssl-dev')
  apt_pkgs+=('libncurses-dev')
  apt_pkgs+=('musl-dev')
  apt_pkgs+=('libboost-all-dev')
  apt_pkgs+=('libtool')
  apt_pkgs+=('linux-libc-dev')
  apt_pkgs+=('libevent-dev')
  apt_pkgs+=('libxt-dev')
  apt_pkgs+=('bison')
  apt_pkgs+=('flex')
  apt_pkgs+=('groff')
  apt_pkgs+=('libc6')

  apt_pkgs+=('gcc')
  apt_pkgs+=('g++')
  apt_pkgs+=('autoconf')
  apt_pkgs+=('automake')
  apt_pkgs+=('pkg-config')
  apt_pkgs+=('make')
  apt_pkgs+=('patch')

  apt_pkgs+=('golang')
  apt_pkgs+=('nodejs')
  apt_pkgs+=('npm')
  apt_pkgs+=('ruby')
  apt_pkgs+=('rubygems')
  apt_pkgs+=('perl')
  apt_pkgs+=('bazel')

  apt_pkgs+=('google-cloud-cli')
  apt_pkgs+=('gcsfuse')
  apt_pkgs+=('kubectl')

  apt_pkgs+=('docker-ce-cli')

  pip_pkgs+=('pyyaml')
  pip_pkgs+=('kubernetes')
  pip_pkgs+=('docker')
  pip_pkgs+=('ansible')

  pip_pkgs+=('gspread')
  pip_pkgs+=('oauth2client')
  pip_pkgs+=('google-auth-oauthlib')
  pip_pkgs+=('google-auth-httplib2 ')
  pip_pkgs+=('google-api-python-client')

  npm_pkgs+=('npm@latest')
  npm_pkgs+=('clasp@latest')

fi

: <<'COMMENT'
  # TODO: dotnet
  apt_pkgs+=('docker-ce')
  apt_pkgs+=('docker-compose-plugin')
  apt_pkgs+=('kubeadm')
  apt_pkgs+=('kubelet')
COMMENT

# install
if type apt  &> /dev/null; then apt  install --fix-missing -y "${apt_pkgs[@]}" || true; fi
if type pip3 &> /dev/null; then pip3 install --upgrade        "${pip_pkgs[@]}" || true; fi
if type npm  &> /dev/null; then npm  install -g               "${npm_pkgs[@]}" || true; fi

#----------------------------------------------------------------
# opt

if type yq &> /dev/null; then

  opt_yml="$(yq -r '."0".deps.opt' "${HOME}/0.yml")"

  cnt="$(echo "${opt_yml}" | yq -r length)"
  for ((i = 0; i < "${cnt}"; i++)); do

    item="$(   echo "${opt_yml}" | yq -r ".["${i}"]")"
    name="$(   echo "${item}"    | yq -r .name)"
    version="$(echo "${item}"    | yq -r .version)"
    latest="$( echo "${item}"    | yq -r .latest)"
    type="$(   echo "${item}"    | yq -r .type)"
    strip="$(  echo "${item}"    | yq -r .strip)"
    url="$(    echo "${item}"    | yq -r .url)"

    dir="${HOME}/opt/${name}"
    if [[ 'null' != "${version}" ]]; then
      dir+="/${version}"
    fi

    mkdir -p "${dir}"
    pushd "${dir}"

      if [[ 'raw' == "${type}" ]]; then
        curl -SLO "${url}"

      elif [[ 'tgz' == "${type}" ]]; then
        curl -SL "${url}" | tar zx --strip-components "${strip}" --no-same-permissions --no-same-owner -C "${dir}"

      elif [[ 'zip' == "${type}" ]]; then
        # TODO: pipe unzip strip
        curl -SL "${url}" | "${HOME}/opt/net.java.jdk/latest/bin/jar" x

      else
        false
      fi

      if [[ 'true' == "${latest}" ]]; then
        ln -fsn "${version}" '../latest'
      fi

    popd

  done

fi

#----------------------------------------------------------------
# container

if type docker &> /dev/null; then

  container_yml="$(yq -r '."0".deps.container' "${HOME}/0.yml")"

  cnt="$(echo "${container_yml}" | yq -r length)"
  for ((i = 0; i < "${cnt}"; i++)); do
    docker pull "$(echo "${container_yml}" | yq -r ".["${i}"]")"
  done

fi

#----------------------------------------------------------------
# config

if type locale-gen &> /dev/null; then
  locale-gen ja_JP.UTF-8
  localedef -f UTF-8 -i ja_JP ja_JP.utf8
  update-locale LANG="ja_JP.UTF-8"
fi
