#!/bin/bash
# ---------------- Linux Shell Script [LF] ----------------
set -o errexit
set -o nounset
set -o pipefail

  jdk_ver='latest'
  JAVA_HOME="${HOME}/opt/net.java.jdk/${jdk_ver}"
  CLASSPATH="${0}"

  "${JAVA_HOME}/bin/java" Entrypoint "$@"

exit "${?}"
