#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cgroup="$(tail -n 1 /proc/1/cgroup)"

# containerd
if [[ "${cgroup}" == '0::/system.slice/containerd.service' ]]; then
  exit 0
fi

# docker run
if [[ "${cgroup}" == '0::/' ]]; then
  exit 0
fi

if is_docker_build; then
  exit 0
fi

exit 1
