#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

#openpgp4fpr="$(grep '^default-key' "${HOME}/.gnupg/gpg.conf" 2> /dev/null | awk -F '=' '{print $2}')"

# TODO: 先頭の鍵を使用
openpgp4fpr="$(gpg --list-secret-keys --with-colons 2> /dev/null | grep ^fpr | head -n 1 | cut -d ':' -f 10)"
test -n "${openpgp4fpr}"

test "${openpgp4fpr}" == "$(gpg --decrypt "${HOME}/src/0.gpg/${openpgp4fpr}.fpr" 2> /dev/null)"

echo "${openpgp4fpr}"
