# hosts
no-hosts
addn-hosts=/etc/hosts.dnsmasq

# acl
domain-needed
bogus-priv

# resolv
strict-order
resolv-file=/etc/resolv.conf.dnsmasq

# domain
expand-hosts
domain=0

# log
log-queries
log-facility=/dev/stdout
