---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${hostname}
  name: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      volumes:
        - {name: data-volume, hostPath: {path: /root/lib/0.pgsql, type: Directory}}
      containers:
        - name: pgsql
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 5432}
          volumeMounts:
            - {name: data-volume, mountPath: /var/lib/postgresql/data}
          env:
            - {name: POSTGRES_PASSWORD, value: pgsql}

---
apiVersion: v1
kind: Service
metadata:
  namespace: ${hostname}
  name: pgsql
spec:
  type: LoadBalancer
  selector:
    app: pgsql
  ports:
    - {protocol: TCP, port: 5432, nodePort: 5432}
