---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "0"
  name: container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      volumes:
        - name: data
          hostPath:
            path: /home/0.container
            type: Directory
      containers:
        - name: container
          image: registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 5000}
          volumeMounts:
            - {name: data, mountPath: /var/lib/registry/docker/registry}

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: container
spec:
  type: LoadBalancer
  selector:
    app: container
  ports:
    - {protocol: TCP, port: 5000}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "0"
  name: container
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: container.0
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: container
                port:
                  number: 5000
