#----------------------------------------------------------------
# server

# org
#server                 pool.ntp.org iburst # NTP Pool Project
server               0.pool.ntp.org iburst
server               1.pool.ntp.org iburst
server               2.pool.ntp.org iburst
server               3.pool.ntp.org iburst

# gov
#server             time-nw.nist.gov iburst # NIST
#server                 ntp.nasa.gov iburst # NASA

# jp.ac
#server         ntp.nc.u-tokyo.ac.jp iburst # 東京大学
#server                ntp.sut.ac.jp iburst # 東京理科大学
#server             ntp.tohoku.ac.jp iburst # 東北大学
#server               higw.tut.ac.jp iburst # 豊橋技術科学大学	
#server eagle.center.osakafu-u.ac.jp iburst # 大阪府立大学
#server         cesium.mtk.nao.ac.jp iburst # 国立天文台
#server     clock.nc.fukuoka-u.ac.jp iburst # 福岡大学
#server     clock.tl.fukuoka-u.ac.jp iburst

# jp.ad
#server          ntp.jst.mfeed.ad.jp iburst # mfeed
#server         ntp1.jst.mfeed.ad.jp iburst
#server         ntp2.jst.mfeed.ad.jp iburst
#server         ntp3.jst.mfeed.ad.jp iburst

# jp.gr
#server               ntp.ring.gr.jp iburst # Ring Server Project
#server              ntp0.ring.gr.jp iburst
#server              ntp1.ring.gr.jp iburst
#server              ntp2.ring.gr.jp iburst

# jp.nict
#server                  ntp.nict.jp iburst # NICT

# com
#server              time.google.com iburst # Google Public NTP
#server             time1.google.com iburst
#server             time2.google.com iburst
#server             time3.google.com iburst
#server             time4.google.com iburst

#----------------------------------------------------------------

allow 10.0.0.0/8
allow 172.16.0.0/12
allow 192.168.0.0/16
