---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: btc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc
  template:
    metadata:
      labels:
        app: btc
    spec:
      volumes:
        - {name: conf-volume, hostPath: {path: /root/src/0.btc/bitcoin/conf, type: Directory}}
        - {name: data-volume, hostPath: {path: /root/lib/0.btc,              type: Directory}}
      containers:
        - name: btc
          image: container.${domain}/org.bitcoin:${tag}
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 8333}
          volumeMounts:
            - {name: data-volume,                        mountPath: /root/.bitcoin}
            - {name: conf-volume, subPath: bitcoin.conf, mountPath: /root/.bitcoin/bitcoin.conf, readOnly: true}

---
apiVersion: v1
kind: Service
metadata:
  namespace: ${namespace}
  name: btc
spec:
  type: NodePort
  selector:
    app: btc
  ports:
    - {protocol: TCP, port: 8333, nodePort: 38333}
