---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "0"
  name: pub
data:
  default.conf: |
    server {
      listen 80;
    # listen 443 ssl;
      server_name _;
      root /usr/share/nginx/html;
      location = / {
      }
      server_tokens        off;
      charset              utf-8;
      autoindex            on;
      autoindex_exact_size on;
      autoindex_localtime  on;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "0"
  name: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      volumes:
        - {name: nginx-volume, configMap: {name: pub}}
        - {name: pub-volume,   hostPath:  {path: /mnt/0.pub, type: Directory}}
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - {protocol: TCP, containerPort: 80}
          volumeMounts:
            - {name: nginx-volume, mountPath: /etc/nginx/conf.d,     readOnly: true}
            - {name: pub-volume,   mountPath: /usr/share/nginx/html, readOnly: true}

---
apiVersion: v1
kind: Service
metadata:
  namespace: "0"
  name: pub
spec:
  type: LoadBalancer
  selector:
    app: pub
  ports:
    - {protocol: TCP, port: 80}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "0"
  name: pub
spec:
  rules:
    - host: pub.0
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pub
                port:
                  number: 80
    - host: pub.${tld}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pub
                port:
                  number: 80
